### ISSUE TITLE
Add to docs

### ISSUE THREAD

**Issue by Bomberski** [D3vil-Design/K1-Max-Manta-Conversion#2]
Add to the "how to"
![image](https://github.com/D3vil-Design/K1-Max-Manta-Conversion/assets/51887282/bcd6e577-4d7c-4472-936e-fbd3f3217164)

**Comment by hihihihinick** [comment]
Yes!!! I was just about to ask if a wiring diag, or perhaps a photo was available. Thanks!

**Comment by Bomberski** [comment]
Closed and did a pull request.
